kind: pipeline
type: docker
name: FantomGames

trigger:
  event:
    - push

steps:

  # build flutter app
  - name: flutter-web-build
    image: ghcr.io/cirruslabs/flutter:3.13.5
    commands:
      - cd ./fantom_games
      - flutter clean
      - flutter pub get
      - flutter build web --no-tree-shake-icons

  # testing flutter code
  - name: flutter-test
    image: ghcr.io/cirruslabs/flutter:3.13.5
    commands:
      - cd ./fantom_games
      - flutter pub get
      - flutter test
      - flutter test --coverage > ./test.output
    depends_on: [ flutter-web-build ]