name: fantom_games
description: Web app for playing and earnings gain

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  http: ^1.1.0
  crypto: ^3.0.3
  shared_preferences: ^2.0.7
  flutter_session_manager: ^1.0.3
  provider: ^6.0.5
  socket_io_client: ^2.0.3+1
  flutter_launcher_icons: ^0.13.1
  mailer: ^6.0.1
  file_picker: ^6.1.1
  image: ^4.1.4
  google_ml_kit: ^0.16.3
  confetti: ^0.7.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  web:
    generate: true
    image_path:  "assets/FantomGamesIcon.png"
  windows:
    generate: true
    image_path:  "assets/FantomGamesIcon.png"
  macos:
    generate: true
    image_path:  "assets/FantomGamesIcon.png"

flutter:
  assets:
    - assets/
    - assets/games/
  uses-material-design: true
  fonts:
    - family: PorterSans
      fonts:
        - asset: fonts/porter-sans-inline-block.otf
    - family: Mistral
      fonts:
        - asset: fonts/CopyofMistral2.ttf
        - asset: fonts/design.graffiti.mistral.ttf
        - asset: fonts/MIST____.TTF
        - asset: fonts/MISTRAL.TTF
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Bubble
      fonts:
        - asset: fonts/RubikBubbles-Regular.ttf
    - family: Marker
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf
    - family: Boog
      fonts:
        - asset: fonts/Boogaloo-Regular.ttf


